- name: Install dropbear-initramfs
  package:
    name: dropbear-initramfs
    state: present

- name: Create authorized_keys link
  file:
    src: /root/.ssh/authorized_keys
    dest: /etc/dropbear-initramfs/authorized_keys
    state: link
  notify: Update initramfs

- name: Set port in /etc/dropbear-initramfs/config
  lineinfile:
    path: /etc/dropbear-initramfs/config
    line: "DROPBEAR_OPTIONS=\"-p {{ dropbear_initramfs_port }}\""
    regexp: "DROPBEAR_OPTIONS"
  notify: Update initramfs

# workaround for https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1876884
- name: Install deconfigure-interfaces initramfs script
  copy:
    src: initramfs-deconfigure-interfaces
    dest: /etc/initramfs-tools/scripts/init-bottom/deconfigure-interfaces
    mode: a+x
  notify: Update initramfs
